/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_HelloJni */

#ifndef _Included_jni_HelloJni
#define _Included_jni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_HelloJni
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_HelloJni_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
